#!/usr/bin/env python
print ('    ')
n = input('Digite algo: ')
print ('    ')
n1 = (type(n))
print (f'Qual é o tipo primitivo: {n1}')
print ('É um Alpha númerico?', n.isalnum())
print ('É um número?', n.isnumeric())
print ('É um N° decimal?', n.isdecimal())
print ('Estes caracteres estão em minusculo?', n.islower())
print ('Estes caracteres estão em maiusculo?', n.isupper())
print ('Só tem espaços?', n.isspace())
print ('É alfabético?', n.isalpha())
print ('Esta capitalizada', n.istitle())
print ('    ')

